### ISSUE TITLE
Describe the bug in one line

### ISSUE THREAD

**Issue by EternityZ4** [diamond-gold/DummyItemsBlocks#14] opened 2023-11-14 12:08 UTC
Fatal error: Declaration of diamondgold\DummyItemsBlocks\tile\DummyTile::addAdditionalSpawnData(pocketmine\nbt\tag\CompoundTag $nbt): void must be compatible with pocketmine\block\tile\Spawnable::addAdditionalSpawnData(pocketmine\nbt\tag\CompoundTag $nbt, pocketmine\network\mcpe\convert\TypeConverter $typeConverter): void in C:\Users\LENOVO\Desktop\Total\IceCubeSV-NW-PM5\IceCubeNW-ROLEPLAY\plugins\DummyItemsBlocks-43e90efa11e4cd07930ea66c608e197b3a9289a4\src\diamondgold\DummyItemsBlocks\tile\DummyTile.php on line 14
[15:37:05.093] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[15:37:05.099] [Server thread/EMERGENCY]: Please upload the "C:/Users/LENOVO/Desktop/Total/IceCubeSV-NW-PM5/IceCubeNW-ROLEPLAY/crashdumps/Tue_Nov_14-15.37.05-+0330_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[15:37:05.100] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by diamond-gold** [comment] 2023-11-14 12:10
Duplicate of #3

**Closed by diamond-gold** 2023-11-14 12:10 UTC
Labels: bug, TBC
