### ISSUE TITLE
campfire

### ISSUE THREAD

**Issue by UnknownNull** [diamond-gold/DummyItemsBlocks#8] opened 2023-09-21 23:01 UTC
campfire not work

**Comment by floriiian** [comment] 2023-09-22 07:19
What he means by "Campfire not work" is that campfires are not placeable anymore and already placed ones get replaced into update-blocks.

**Comment by diamond-gold** [comment] 2023-09-22 09:33
Duplicate of #7

**Closed by diamond-gold** 2023-09-22 09:33 UTC
Labels: bug, TBC
